name: sr-extension-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - opencv
  - pip:
    - jupyter
    - tensorflow==2.9.1
    - tensorflow_datasets
    - git+https://github.com/rfforelli/hls4ml_accum_concat.git@main#egg=hls4ml[profiling]
    - qkeras==0.9.0
    - scikit-learn
